apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: pathfinder-server
    bundle: pathfinder-{{ .Values.version }}
  name: pathfinder-server
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: pathfinder-server
    deploymentconfig: pathfinder-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  creationTimestamp: null
  labels:
    app: pathfinder-ui
    application: pathfinder-ui
    bundle: pathfinder-{{ .Values.version }}
  name: pathfinder-ui
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: pathfinder-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
