apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
  labels:
    template: mongodb-persistent-template
  name: {{ .Values.database_service_name }}
spec:
  ports:
  - name: mongo
    nodePort: 0
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: {{ .Values.database_service_name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
